/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        System.out.println(getQuote());
    }

    public static String getQuote(){
        try {
            URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();

            BufferedReader reader = new BufferedReader(new InputStreamReader(con.getInputStream()));

            Gson gson = new Gson();
            Quote quoteFromApi = gson.fromJson(reader, Quote.class);

            //get all quotes from file
            BufferedReader json = new BufferedReader(new FileReader("./resources/recentquotes.json"));
            Quote[] quote = gson.fromJson(json, Quote[].class);

            //add all quotes into list
            List<Quote> quoteList = new ArrayList<>();

            for (int i = 0; i < quote.length; i++){
                quoteList.add(quote[i]);
            }

            //add the quote from API into list
            quoteList.add(quoteFromApi);

            //write quote list to file and change to Json
            FileWriter fileWriter = new FileWriter("./resources/recentquotes.json");
            gson.toJson(quoteList, fileWriter);
            fileWriter.close();

            return quoteFromApi.quoteText;

        }catch (IOException e){
            System.out.println(e);
            try {
                Gson gson = new Gson();

                BufferedReader json = new BufferedReader(new FileReader("./resources/recentquotes.json"));
                Quote[] quote = gson.fromJson(json, Quote[].class);

                int random = (int) (Math.random() * quote.length);
                return quote[random].text;

            }catch (FileNotFoundException e1){
                System.out.println(e1);
                return "File not found";
            }
        }

    }
}

