/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {
    public static void main(String[] args){
        try {
            Gson gson = new Gson();

            BufferedReader json =  new BufferedReader(new FileReader("../../../resources/recentquotes.json"));
            Quote[] quote = gson.fromJson(json, Quote[].class);

            int random = (int)(Math.random() * quote.length);
            Quote output = quote[random];

            System.out.println(output);

        } catch (IOException e){
            e.printStackTrace();
        }
    }

}
